---
# Source: mongodb/templates/pvc.yaml

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongodb
    chart: mongodb-5.1.0
    heritage: Tiller
    release: mongodb
  name: mongodb
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: mongodb/templates/svc.yaml

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-5.1.0
    release: "mongodb"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongodb
    release: "mongodb"

---
# Source: mongodb/templates/deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    chart: mongodb-5.1.0
    release: "mongodb"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: mongodb
      release: "mongodb"
  template:
    metadata:
      labels:
        app: mongodb
        release: "mongodb"
        chart: mongodb-5.1.0
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: mongodb
        image: docker.io/bitnami/mongodb:4.0.3
        imagePullPolicy: "Always"
        env:
        - name: MONGODB_USERNAME
          value: ""
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "1"
        - name: MONGODB_DATABASE
          value: "db"
        - name: MONGODB_ENABLE_IPV6
          value: "yes"
        - name: MONGODB_EXTRA_FLAGS
          value: 
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          {}
          

      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb
---
# Source: mongodb/templates/configmap.yaml

---
# Source: mongodb/templates/secrets.yaml


